"""empty message

Revision ID: 0446a9baa6ff
Revises: e7efa207cc92
Create Date: 2021-05-21 05:59:14.802738+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0446a9baa6ff'
down_revision = 'e7efa207cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.sql.func.now()))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.sql.func.now()))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
