"""empty message

Revision ID: e7efa207cc92
Revises: 4fc10048ad44
Create Date: 2021-05-21 05:57:48.609729+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7efa207cc92"
down_revision = "4fc10048ad44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "useraddress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(length=100), nullable=True),
        sa.Column("zip_code", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.sql.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=True, onupdate=sa.sql.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("useraddress")
    # ### end Alembic commands ###
