-- upgrade --
ALTER TABLE `user` ADD `email` VARCHAR(254)  UNIQUE;
ALTER TABLE `user` ADD `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE `user` ADD `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
-- downgrade --
ALTER TABLE `user` DROP COLUMN `email`;
ALTER TABLE `user` DROP COLUMN `created_at`;
ALTER TABLE `user` DROP COLUMN `updated_at`;
